"""fix message

Revision ID: c292b7a509cf
Revises: ec5df7b2e61e
Create Date: 2024-05-28 19:25:44.091368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c292b7a509cf'
down_revision: Union[str, None] = 'ec5df7b2e61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_reply_to_message', table_name='messages')
    op.create_unique_constraint('uc_message', 'messages', ['original_id', 'source'])
    op.drop_column('messages', 'reply_to_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_message', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint('uc_message', 'messages', type_='unique')
    op.create_index('ix_messages_reply_to_message', 'messages', ['reply_to_message'], unique=True)
    # ### end Alembic commands ###
