"""fix message (original_parent_id)

Revision ID: d2beb324d6eb
Revises: bfc9838a2a7e
Create Date: 2024-05-28 19:38:29.084212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2beb324d6eb'
down_revision: Union[str, None] = 'bfc9838a2a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'original_parent_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index('ix_messages_original_parent_id', table_name='messages')
    op.create_index(op.f('ix_messages_original_parent_id'), 'messages', ['original_parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_original_parent_id'), table_name='messages')
    op.create_index('ix_messages_original_parent_id', 'messages', ['original_parent_id'], unique=True)
    op.alter_column('messages', 'original_parent_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
