"""add message

Revision ID: ec5df7b2e61e
Revises: 50bfb3770978
Create Date: 2024-05-28 19:19:11.700761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec5df7b2e61e'
down_revision: Union[str, None] = '50bfb3770978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('original_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('original_parent_id', sa.BigInteger(), nullable=False),
    sa.Column('reply_to_message', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(), server_default='tg', nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_original_id'), 'messages', ['original_id'], unique=True)
    op.create_index(op.f('ix_messages_original_parent_id'), 'messages', ['original_parent_id'], unique=True)
    op.create_index(op.f('ix_messages_reply_to_message'), 'messages', ['reply_to_message'], unique=True)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_messages_user_name'), 'messages', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_user_name'), table_name='messages')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_reply_to_message'), table_name='messages')
    op.drop_index(op.f('ix_messages_original_parent_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_original_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
